version: "3.1"

services:
    mongo:
        image: mongo
        volumes:
            - db-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root

    php:
        build:
            context: docker/build/php
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
             - ./:/app

    nginx:
        image: nginx:1.19
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/app
            - ./docker/deploy/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf

volumes:
    db-data:
        driver: local
